#release configuration
#Wed Mar 06 16:27:08 UTC 2024
projectVersionPolicyId=default
project.scm.io.github.idirze\:kdp-spark-auth-filter.url=https\://github.com/idirze/okdp-spark-auth-filter.git
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
pinExternals=false
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
pushChanges=false
project.scm.io.github.idirze\:kdp-spark-auth-filter.connection=scm\:git\:https\://github.com/idirze/okdp-spark-auth-filter.git
project.scm.io.github.idirze\:kdp-spark-auth-filter.tag=HEAD
project.rel.io.github.idirze\:kdp-spark-auth-filter=0.0.3-RC11
project.scm.io.github.idirze\:kdp-spark-auth-filter.developerConnection=scm\:git\:https\://github.com/idirze/okdp-spark-auth-filter.git
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
remoteTagging=true
releaseStrategyId=default
scm.commentPrefix=[maven-release-plugin] 
completedPhase=end-release
scm.url=scm\:git\:https\://github.com/idirze/okdp-spark-auth-filter.git
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.tagNameFormat=v@{project.version}
exec.additionalArguments=-Dpassword\=null
project.dev.io.github.idirze\:kdp-spark-auth-filter=0.0.4-SNAPSHOT
scm.tag=v0.0.3-RC11
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
